<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF0tytcv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF0tytcv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerF0tytcv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerF0tytcv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerF0tytcv\appProdProjectContainer([
    'container.build_hash' => 'F0tytcv',
    'container.build_id' => 'bb00688b',
    'container.build_time' => 1564478566,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF0tytcv');
