<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFgzwzgf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFgzwzgf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFgzwzgf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFgzwzgf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFgzwzgf\appProdProjectContainer([
    'container.build_hash' => 'Fgzwzgf',
    'container.build_id' => '1b3a5245',
    'container.build_time' => 1563957218,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFgzwzgf');
