<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0wiq1fg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0wiq1fg/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0wiq1fg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0wiq1fg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0wiq1fg\appProdProjectContainer([
    'container.build_hash' => '0wiq1fg',
    'container.build_id' => '6cf25798',
    'container.build_time' => 1564645306,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0wiq1fg');
