<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjde4nn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjde4nn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLjde4nn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLjde4nn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLjde4nn\appDevDebugProjectContainer([
    'container.build_hash' => 'Ljde4nn',
    'container.build_id' => '6dee0c66',
    'container.build_time' => 1568019666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjde4nn');
