<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJwfvwde\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJwfvwde/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJwfvwde.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJwfvwde\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJwfvwde\appDevDebugProjectContainer([
    'container.build_hash' => 'Jwfvwde',
    'container.build_id' => 'f69e4a78',
    'container.build_time' => 1563955644,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJwfvwde');
